Feat/figure new
mathpresso/qmwp pull request #11
Opened 2022-12-29 08:10 UTC by feidfoe

2023-01-02 05:06 UTC, pocca2048 requested changes

2023-01-02 05:06 UTC, pocca2048 commented on generators/figure.py
> +            'n0 = {diag}\nt0 = 2 * n0\nt1 = diagonal_inv(n0)\nt2 = 2 * t1\nanswer = t0 + t2'),
새로 함수 정의하신 건 `utils.predefined_func`에 넣어주셔야 합니다.

2023-01-02 05:06 UTC, pocca2048 commented on generators/figure.py
> +    A = pick_e(choice(PEOPLE_NAMES))
`pick_e` 함수를 import를 안 해서 에러가 나오네요. 이외에도 몇 가지 import가 안 된 것들이 있는 것 같습니다. 테스트 부탁드립니다.

2023-01-02 05:08 UTC, feidfoe commented on generators/figure.py
> +    A = pick_e(choice(PEOPLE_NAMES))
이전 것들도 딱히 테스트를 하지는 않았는데, 
`python main.py -o problem.json -n 100`
에서 에러가 나지 않도록 설정하면 되나요?

2023-01-02 05:10 UTC, pocca2048 commented on generators/figure.py
> +    A = pick_e(choice(PEOPLE_NAMES))
넵 맞습니다

2023-01-06 10:14 UTC, feidfoe commented
@pocca2048 수정했습니다.

2023-01-09 02:19 UTC, pocca2048 approved these changes
LGTM

2023-01-09 02:28 UTC, merged